apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vlfk-no
resources:
  - ../../../base
patchesStrategicMerge:
  - config-map.yaml
commonLabels:
  app.kubernetes.io/name: fint-flyt-history-service
  app.kubernetes.io/instance: fint-flyt-history-service_vlfk-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-flyt
  fintlabs.no/team: flyt
  fintlabs.no/org-id: vlfk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/routes/0/match"
        value: "Host(`flyt.vigoiks.no`) && PathPrefix(`/alpha/vlfk-no/api/intern/historikk`)"
    target:
      kind: IngressRoute
      name: fint-flyt-history-service
  - patch: |-
      - op: replace
        path: "/spec/acls/0/topic"
        value: "vlfk-no.flyt.*"
    target:
      kind: KafkaUserAndAcl
      name: fint-flyt-history-service

